[package]
name = "network-monitor-esp-rs-no-std"
version = "0.1.0"
authors = ["Ivan Li <ivanli2048@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
hal             = { package = "esp32c3-hal", version = "0.15.0", features=["embassy", "async", "embassy-time-timg0"] }
esp-backtrace   = { version = "0.10.0", features = ["esp32c3", "panic-handler", "exception-handler", "print-uart"] }
esp-println     = { version = "0.8.0", features = ["esp32c3"] }
embassy-executor = { version = "0.5.0"}
embassy-time = "0.3.0"

