name: Build Firmware

on:
  workflow_dispatch:
    inputs:
      ssid:
        description: 'WiFi SSID'
        required: true
        type: string
      password:
        description: 'WiFi Password'
        required: true
        type: string
      server_address:
        description: 'Server Address (IP:PORT)'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: nightly
        targets: riscv32imc-unknown-none-elf
        components: rust-src
        
    - name: Install tools
      run: |
        cargo install espflash
        cargo install cargo-binutils
      
    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Build firmware
      env:
        SSID: ${{ inputs.ssid }}
        PASSWORD: ${{ inputs.password }}
        SERVER_ADDRESS: ${{ inputs.server_address }}
      run: cargo build --release

    - name: Generate binary file and build info
      run: |
        cargo objcopy --release -- -O binary firmware.bin
        ls -la firmware.bin
        echo "Build Information" > build-info.txt
        echo "=================" >> build-info.txt
        echo "Build Date: $(date)" >> build-info.txt
        echo "Git Commit: ${{ github.sha }}" >> build-info.txt
        echo "WiFi SSID: ${{ inputs.ssid }}" >> build-info.txt
        echo "Server Address: ${{ inputs.server_address }}" >> build-info.txt
        echo "Firmware Size: $(stat -c%s firmware.bin) bytes" >> build-info.txt
        cat build-info.txt

    - name: Upload firmware artifact
      uses: actions/upload-artifact@v3
      with:
        name: firmware-${{ github.run_number }}
        path: |
          target/riscv32imc-unknown-none-elf/release/network-monitor-esp-rs-no-std
          firmware.bin
          build-info.txt
        retention-days: 30
